name: Daily Newsletter Generator

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  run-newsletter:
    runs-on: ubuntu-latest

    GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🛠️ Run Newsletter Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        run: |
          python auto_newsletter.py
